# Generated by Django 4.2.6 on 2023-11-21 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
