# Generated by Django 4.2.6 on 2023-11-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driving_license',
            field=models.ImageField(blank=True, null=True, upload_to='user_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='inspection_report',
            field=models.ImageField(blank=True, null=True, upload_to='user_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='insurance',
            field=models.ImageField(blank=True, null=True, upload_to='user_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='log_book',
            field=models.ImageField(blank=True, null=True, upload_to='user_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.ImageField(blank=True, null=True, upload_to='user_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_documents/'),
        ),
    ]
