# Generated by Django 4.2.6 on 2023-11-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_driving_license_user_inspection_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
